import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Box, SimpleGrid, Icon, Text, Stack, Flex } from "@chakra-ui/react";
import { FcAssistant, FcDonate, FcInTransit } from "react-icons/fc";

const Feature = ({ title, text, icon }) => {
  return (
    <Stack
      border={"1px solid"}
      textAlign="center"
      p={"10px"}
      borderRadius="10px"
    >
      <Flex
        w={16}
        h={16}
        align={"center"}
        justify={"center"}
        color={"white"}
        rounded={"full"}
        bg={"gray.100"}
        mb={1}
        margin={"auto"}
      >
        {icon}
      </Flex>
      <Text fontWeight={600}>{title}</Text>
      <Text color={"gray.600"}>{text}</Text>
    </Stack>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.banners}>
        <div className={styles.partOne}>
          <Image
            src="/1.png"
            alt="Picture of the author"
            width={460}
            height={150}
          />
          <Image
            src="/11.png"
            alt="Picture of the author"
            width={600}
            height={150}
          />
          <Image
            src="/3.png"
            alt="Picture of the author"
            width={455}
            height={150}
          />
        </div>
        <div className={styles.partTwo}>
          <Image
            src="/2.png"
            alt="Picture of the author"
            width={455}
            height={150}
          />
          <Image
            src="/4.png"
            alt="Picture of the author"
            width={460}
            height={150}
          />

          <Image
            src="/22.png"
            alt="Picture of the author"
            width={600}
            height={150}
          />
        </div>
      </div>

      <Box p={4}>
        <SimpleGrid columns={{ base: 1, md: 3 }} spacing={10}>
          <Feature
            icon={<Icon as={FcAssistant} w={10} h={10} />}
            title={"Lifetime Support"}
            text={
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore..."
            }
          />
          <Feature
            icon={<Icon as={FcDonate} w={10} h={10} />}
            title={"Unlimited Donations"}
            text={
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore..."
            }
          />
          <Feature
            icon={<Icon as={FcInTransit} w={10} h={10} />}
            title={"Instant Delivery"}
            text={
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore..."
            }
          />
        </SimpleGrid>
      </Box>
    </>
  );
}
